### ISSUE TITLE
Windows builds are broken

### ISSUE THREAD

**Issue by cup** [compnerd/swift-win32#12]
If you go here:

https://dev.azure.com/compnerd/swift-build/_dashboards/dashboard/96ff9e56-df29-4472-acb1-911a4264b3e5

3 options are available for the SDK:

- Swift SDK for Windows
- Swift SDK for Windows (VS2017) - by Facebook
- Swift SDK for Windows (VS2019) - by Facebook

but those pipelines have no successful builds, and the pipelines have even been
deleted. Also I see these:

- Swift 5.2 Toolchain for Windows x64 (VS2017)
- Toolchain for Windows x64 (VS2017)
- Toolchain for Windows x64 (VS2019)

but I tried downloading one and stopped at 700 MB. What is going on? Even
Haskell is not that big.

**Comment by compnerd** [comment]
This is the same as #11.  The builds were taking much longer to get through because the older pipelines would be running as well.  As things are being shuffled they would also break and made it harder to restructure the builds.  You’re welcome to help fix the issues, I’m repairing them as fast as possible, the issues take 6-8 hours to surface.

As to the size, that is what it should be.  This is not Haskell.  It’s a C/C++/swift toolchain with a linker, debugger, assembler, binary tools, and IDE tooling.  Unfortunately, the non-packaged form also has some testing tools (this is due to build setup in swift) which also adds size.  So, yes, the expectation is that it is about 3G.

**Comment by compnerd** [comment]
BTW, this repository is not for the builds, this is the Swift/Win32 repository.  The builds are part of the compnerd/swift-build repository

**Comment by cup** [comment]
I just want to compile swift files into executable files for Windows

are you telling me that takes a 3 GB download?

Do you realize that is 10 times larger than the download for any other programming language?

**Comment by compnerd** [comment]
Yes, that’s the current build configuration.  You could build it yourself if you are looking for something smaller.  In order to ensure that things don’t regress, the builds need to contain everything.

**Comment by cup** [comment]
I just won't use the Swift programming language then, as that is comically large. Thank you for your comments.

**Comment by compnerd** [comment]
I am not a Windows developer, I am a compiler engineer.  I'm trying to figure out things as I go along.  I am happy to accept patches to fix the installer to avoid copies of the clang binaries and the llvm binaries rather than symbolic links since the Windows file system does not support that primitive until an experimental release recently.  Even then, there are permission issues that that causes.  I think that fixing the Windows file system to support symbolic links should help cut down the image by ~2G.  The linux version of the toolchain is ~700M, so that should be something that the Windows toolchain can reach.  Im a single person, Im doing as much as possible to support the work, but it needs people who understand the Windows technologies to help.

**Comment by compnerd** [comment]
https://compnerd.visualstudio.com/swift-build/_build/results?buildId=22989&view=results is the last build for the 5.2 toolchain that went through.  The toolchain itself is a 2.3G zip, the SDK is 70M zip.

**Comment by cup** [comment]
70M sounds great - I will test when I get home - thank you very much.

**Comment by cup** [comment]
@compnerd I dont think thats right - I downloaded the SDK, but it only has `plutil.exe`, no way to compile to interpret

**Comment by compnerd** [comment]
Correct.  The SDK is to be used in conjunction with the toolchain.  There are SDKs for Android, Windows, and Linux, and different architectures even.  The toolchain is what enables you to actually build the code.  You instruct the toolchain where the SDK resources are at compile time.  Then you bundle the runtime portions with your application to enable people to run the resulting binaries.  The interpreter doesn’t currently work very well on Windows.  Unfortunately, the bulls have been taking really long to get working which is preventing me from getting back to the interpreter issues in lldb.

**Comment by compnerd** [comment]
FWIW, as I've been reworking the builds, I've been working on getting MSIs generated for the toolchain.  Although the SDK MSIs are not yet ready, it seems that the MSI for the toolchain is ~295 MiB, while the zipped artifacts are ~2.3 GiB.  I hope to have the SDK and runtime available in MSI form as well (though again, it is slow going since this really requires quite a bit of reading for me).  If someone with knowledge would help out, it would probably go much faster.
