### ISSUE TITLE
Examples don't run with SPM

### ISSUE THREAD

**Issue by Mart-Bogdan** [compnerd/swift-win32#645]
1. git clone https://github.com/compnerd/swift-win32
2. cd swift-win32
3. swift build  --product Calculator
4. cd .build\x86_64-unknown-windows-msvc\debug
5. Calculator.exe

**Expected result:** see calculator sample
**Actual result:**   I can see error log in console, and app isn't shuting down until I press Ctrl+C:

```
2021-07-12T12:01:37+0300 error org.compnerd.swift-win32 : [SwiftWin32] InitCommonControlsEx: Win32 Error 0 - The operation completed successfully.
```
Microsoft Windows [Version 10.0.19042.1083]

compnerd.org Swift version 5.4.2 (swift-5.4.2-RELEASE)
Target: x86_64-unknown-windows-msvc

**Comment by compnerd** [comment]
This is expected behaviour.  You failed to follow the directions for building with SPM.  The recommended build system is CMake for exactly this reason.  There are things which SPM is yet incapable of doing, and so there are extra steps that you must do after each build.

Please read through the instructions at https://github.com/compnerd/swift-win32/blob/main/README.md

**Comment by Mart-Bogdan** [comment]
What is SPM?

I've noticed that I need cmake in readme, but when I run build it linked successfully. So I decided that all is ok, or perhaps it was able to locate CMake from CLion installation. Shpouldn't it fail build then?

**Comment by Mart-Bogdan** [comment]
Thanks for your comments. I was able to build with manual steps from the readme. CMake fails for me, but perhaps it's my lack of experience with CMake.

So the root of a problem was missing manifest? Perhaps it should fail with error other than `0 -- no error`

I've just checked, the problem is not in manifest! Without manifest controls just looks ugly, but works. The problem is in Info.plst, I guess the program tries to read it and fails silently.

**Comment by compnerd** [comment]
> What is SPM?

SPM is the Swift Package Manager.

> So the root of a problem was missing manifest?

Partially; the manifest is needed for the controls to behave as expected as there are places where the code assumes that the modern behaviour of common controls is enabled.

> The problem is in Info.plst, I guess the program tries to read it and fails silently.

The application actually does not fail - it behaves as it should.  The default behavior is the correct, desirable behaviour - it just silently runs the application main loop.  The general expectation is to use the `Info.plist` to inform the framework of the principal class to instantiate rather than hardcoding that into the application itself. 

> Perhaps it should fail with error other than` 0 -- no error`

The `0 -- no error` is something that I've not been able to chase down, but it is a result of a refactoring that someone else had done with the `TableView` with the reparenting IIRC.  I'd love patches to get that reparenting issue resolved.
